### ISSUE TITLE
JsonEncode with proxies

### ISSUE THREAD

**Issue by crazytyper** [mcuadros/go-candyjs#2]
Hi there,

While playing around with your excellent library i noticed a problem when using `JsonEncode` with a proxy (or with an object containing a proxy).

```
FATAL 56: uncaught error
PANIC 56: uncaught error (calling abort)
SIGABRT: abort
PC=0x7fff8772d0ae
signal arrived during cgo execution

goroutine 7 [syscall, locked to thread]:
runtime.cgocall_errno(0x40030f0, 0xc2080f1280, 0x0)
	/usr/local/go/src/runtime/cgocall.go:130 +0xf5 fp=0xc2080f1260 sp=0xc2080f1238
github.com/olebedev/go-duktape._Cfunc_duk_json_encode(0x5c04130, 0xffffffff, 0x0)
	github.com/olebedev/go-duktape/_obj/_cgo_gotypes.go:882 +0x44 fp=0xc2080f1280 sp=0xc2080f1260
github.com/olebedev/go-duktape.(*Context).JsonEncode(0xc2080320d0, 0xffffffffffffffff, 0x0, 0x0)
```

The problem can be reproduced with the following unit test

```go
func (s *CandySuite) TestPushProxyJson(c *C) {
	s.ctx.PushGlobalObject()
	s.ctx.PushObject()
	// note: it works when using a struct instead of a proxy!
	// s.ctx.PushStruct(&MyStruct{Int: 142})
	s.ctx.PushProxy(&MyStruct{Int: 142})
	s.ctx.PutPropString(-2, "obj")
	s.ctx.PutPropString(-2, "foo")
	s.ctx.Pop()

	// note: also fails with script `foo`   
	err := s.ctx.PevalString(`foo.obj`)

	c.Assert(err, IsNil)
	s.ctx.JsonEncode(-1) // *BOOOM*!
}
```

Any ideas why it fails and/or how to fix this?
thanx.

**Comment by mcuadros** [comment]
The problem is that you cannot serialise a `Proxy`, if you try with a print the same error happens

```go
err := s.ctx.PevalString(`print(foo.obj);`)
c.Assert(err, IsNil);
``` 

in the other hand, if you try with: 

```go
func (s *CandySuite) TestPushProxyJson(c *C) {
	s.ctx.PushGlobalObject()
	s.ctx.PushObject()
	// note: it works when using a struct instead of a proxy!
	// s.ctx.PushStruct(&MyStruct{Int: 142})
	s.ctx.PushProxy(&MyStruct{Int: 142})
	s.ctx.PutPropString(-2, "obj")
	s.ctx.PutPropString(-2, "foo")
	s.ctx.Pop()

	// note: also fails with script `foo`
	err := s.ctx.PevalString(`foo.obj.int`)

	c.Assert(err, IsNil)
	c.Assert(s.ctx.JsonEncode(-1), Equals, "142")
}
```
it works because the result of `foo.obj.int` is not a proxy is a real int. 

BTW Are you using candyjs in something or just playing with it?

**Comment by crazytyper** [comment]
I dug into `duktape.c` and searched the debug trace. It appears duktape attempts to dynamically add a method named `toJson` to the proxy. This attempt fails and causes the panic.

To prove my theory I added method 

```go
func (m *MyStruct) ToJSON(ctx interface{}) interface{} {
	return m
}
```
and surprise, surprise: serialisation suddenly works. 

I also tried adding implementations for `isExtensible` and `preventExtensions` to the proxy, but without any luck. ducktape still tries to add method `toJson`and fails.

At least there is a workaround, although it is very weird :)

PS: currently i am just playing ...

**Comment by mcuadros** [comment]
Maybe a method `ToJSON` can be added to the proxy to handle this request, the simple solution is return `[candyjs proxy]` and the complex one is return the real data serialised. I will take a look later.

**Comment by mcuadros** [comment]
@crazytyper  here is the fix, to I fixed a couple of other similar errors. Thanks! 

Also was a real bug I answered closing the issue, sorry for that.

**Comment by crazytyper** [comment]
great! many thanks.

never mind closing the issue. my 1st reaction would probably have been the same.
